name: Generate feeds and site

on:
  push:
    branches: [ main ]
  schedule:
    # NOTE: UTCなので9時間引く
    # 1日2回実行
    - cron: 0 23,15 * * 0-6
  workflow_dispatch:

jobs:
  generate-feed:
    name: Generate Feed
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      pull-requests: write
      contents: write
      repository-projects: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: yarn

      - name: Install node packages
        run: yarn install

      - name: Get date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache feed images
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-feed-images-${{ steps.get-date.outputs.date }}

      - name: Generate feed
        run: yarn feed-generate

      - name: Generate site
        run: yarn site-build

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # NOTE: 変更履歴が必要な場合は false に変更
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'